config/routes.rb
Ohimy::Application.routes.draw do

  devise_for :users

  match 'book/u/:id/' => 'book#show', :as => :ubook

  namespace :admin do
    root :to => 'home#admin'
    resources :users
    resources :products
  end
  root :to => "home#index"
  match '/welcome' => 'home#welcome'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
# encoding: utf-8
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  embeds_many :avatars
  references_many :twitters
  references_many :comments
  has_many :favorites
  
  field :name
  field :email
  field :sex, default: ""
  field :birthday, type: Date
  field :credit, type: Integer
  field :taobaoid
  field :role, type: Integer, default: 0
  
  
  validates_presence_of :name, :email
  validates_uniqueness_of :name, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :role, :birthday, :sex

end

app/controllers/admin/users_controller.rb
# encoding: utf-8
class Admin::UsersController < AdminController
  def index
    @users = User.where(:role => 0)
  end

  def edit
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    params[:user][:name].split(',').each_with_index do |nick,index|
      params[:user][:name] = nick
      params[:user][:email] = "robot#{DateTime.now.to_i}#{index}@ohimy.com"
      params[:user][:sex] = ['男','女','秘密'][rand(3)]
      params[:user][:birthday] = Date.new(1970+rand(30),rand(12)+1,rand(28)+1)

      params[:user][:created_at] = Date.today - rand(300).day
      
      @user = User.create(params[:user])
    end
    redirect_to :action=>'index'
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to admin_user_path @user
    else
      render :action => "show"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<%= javascript_include_tag 'city' %>
<div class="mainarea">
  <div class="maininner">

    <%= form_for [:admin, @user] do |f| %>
      <div class="bdrcontent">
        <div class="title">
          <h3><%= @user[:nick] %> 基本信息</h3>
        </div>
        <table cellspacing="0" cellpadding="0" class="formtable">
          <tbody><tr><th style="width:12em;">用户名</th>
              <td><a href="/u/<%= @user[:id] %>" target="_blank"><%= @user[:nick] %></a></td></tr>


            <tr><th>开通时间</th><td><%= @user[:created_at] %></td></tr>
            <tr><th>更新时间</th><td><%= @user[:last_request_at] %></td></tr>
            <tr><th>上次登录</th><td><%= @user[:last_login_at] %></td></tr>
            <tr><th>上次IP</th><td><%= @user[:last_login_ip] %></td></tr>
            <tr><th>好友数</th><td><%= @user.followers.size %></td></tr>
            <tr><th>查看数</th><td></td></tr>
            <tr><th>批量管理</th>
              <td>
                <a href="admincp.php?ac=blog&amp;uid=1&amp;searchsubmit=1" target="_blank">日志(0)</a> |
                <a href="admincp.php?ac=album&amp;uid=1&amp;searchsubmit=1" target="_blank">相册(0)</a> |
                <a href="admincp.php?ac=thread&amp;uid=1&amp;searchsubmit=1" target="_blank">话题(0)</a> |
                <a href="admincp.php?ac=poll&amp;uid=1&amp;searchsubmit=1" target="_blank">投票(0)</a> |
                <a href="admincp.php?ac=event&amp;uid=1&amp;searchsubmit=1" target="_blank">活动(0)</a> |
                <a href="admincp.php?ac=doing&amp;uid=1&amp;searchsubmit=1" target="_blank">记录(0)</a> |
                <a href="admincp.php?ac=share&amp;uid=1&amp;searchsubmit=1" target="_blank">分享(0)</a> |
                <a href="admincp.php?ac=feed&amp;uid=1&amp;searchsubmit=1" target="_blank">事件</a> |
                <a href="admincp.php?ac=pic&amp;uid=1&amp;searchsubmit=1" target="_blank">图片</a> |
                <a href="admincp.php?ac=comment&amp;authorid=1&amp;searchsubmit=1" target="_blank">评论</a> |
                <a href="admincp.php?ac=post&amp;uid=1&amp;searchsubmit=1" target="_blank">回帖</a>
              </td></tr>

          </tbody></table>
      </div>
      <br>
      <div class="bdrcontent">
        <div class="title">
          <h3><%= @user[:nick] %> 个人资料</h3>
        </div>
        <table cellspacing="0" cellpadding="0" class="formtable">
          <tbody><tr><th style="width:12em;">头像</th><td><a href="/u/<%= @user[:id] %>" target="_blank"><%= image_tag avatar(@user,:l) %></a>
                <br>[<a href="admincp.php?ac=space&amp;op=deleteavatar&amp;uid=1">删除头像</a>]
              </td></tr>


            <tr>
              <th style="width:12em;">常用邮箱</th>
              <td>
                <%= f.text_field :email, :class=>'t_input' %>
              </td>
            </tr>
            <tr><th style="width:12em;">昵称</th><td><%= f.text_field :nick, :class=>'t_input',:size=>20 %></td></tr>


            <tr><th>清空自定义CSS</th><td>
                <input type="radio" name="clearcss" value="0" checked=""> 不处理
                <input type="radio" name="clearcss" value="1"> 清空
                <p>用户自定义的CSS如果存在恶意代码，可以选择清空。</p>
              </td></tr>

            <tr>
              <th>性别</th>
              <td>
                <%= f.select :sex, [nil,'男','女','秘密'] %>
              </td>
            </tr>
            <tr>
              <th>生日</th>
              <td>
                <%= f.date_select :birthday, {:start_year => 1970, :use_month_numbers => true } %>
              </td>
            </tr>
            <tr>
              <th>居住地</th>
              <td>
                <%= f.select :province, {} %>
                &nbsp;&nbsp;
                <%= f.select :city, {} %>
              </td>
            </tr>
            <tr>
              <th>移动电话</th>
              <td>
                <%= f.text_field :mobile,:size=>20 %>
              </td>
            </tr>
          </tbody></table>
      </div>
      <br/>
      <div class="bdrcontent">
        <div class="title">
          <h3><%= @user[:nick] %> 淘宝认证</h3>
        </div>
        <table cellspacing="0" cellpadding="0" class="formtable">
          <tbody><tr><th style="width:12em;">淘宝ID</th><td>
                <%= f.text_field :taobaoid,:size=>20 %>
                <input type="radio" name="namestatus" value="0" checked=""> 认证失败
                <input type="radio" name="namestatus" value="1"> 认证通过
              </td></tr>
          </tbody></table>
      </div>
      <br>
      <div class="bdrcontent">
        <div class="title">
          <h3><%= @user[:nick] %> 积分、经验值、空间大小管理</h3>
        </div>
        <table cellspacing="0" cellpadding="0" class="formtable">
          <tbody><tr><th style="width:12em;">额外空间大小</th><td>
                <input type="text" class="t_input" name="addsize" value="0" size="10"> M</td></tr>
            <tr><th>积分数</th><td><%= f.text_field :credit,:size=>10 %></td></tr>
            <tr><th>经验值</th><td><%= f.text_field :exp,:size=>10 %></td></tr>
          </tbody></table>
      </div>
      <br>
      <div class="bdrcontent">
        <div class="title">
          <h3><%= @user[:nick] %> 保护信息</h3>
        </div>
        <table cellspacing="0" cellpadding="0" class="formtable">

          <tbody><tr><th style="width:12em;">用户组</th><td>
                <%= f.select :role, {'不限制'=>'','普通会员'=>0,'机器人'=>1,'站点管理员'=>88} %>

                <p>普通用户组，会自动根据用户经验数目的多少进行自动升级/降级<br>系统用户组，用户的身份不受经验值影响</p></td></tr>

            <tr><th>删除保护</th><td>
                <input type="radio" name="flag" value="0"/> 不保护
                <input type="radio" name="flag" value="1" checked=""/> 保护
                <p>保护状态下，该用户将不能够被删除。</p>
              </td></tr>

          </tbody></table>
        <script type="text/javascript">
          initPlace('<%= @user[:city] %>','<%= @user[:province] %>');
          function showDateSet(val) {
            var expObj = $("expirationtr");
            expObj.style.display = parseInt(val) ? '' : 'none';
          }
        </script>
      </div>

      <div class="footactions">
        <%= f.submit '提交',:class=>'submit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="mainarea">
  <div class="maininner">

    <div class="tabs_header">
      <ul class="tabs">
        <li class="active"><a href="/admin/users"><span>管理用户</span></a></li>
		<li><a href="<%= new_admin_user_path %>"><span>新建用户</span></a></li>
      </ul>
    </div>

    <%= form_for :search, :url => admin_users_path do |f| %>
      <div class="block style4">
        <table cellspacing="3" cellpadding="3">
          <tbody><tr>
              <th>用户UID</th><td><%= f.text_field :id_equals,:size=>10 %></td>
              <th>昵称</th><td><%= f.text_field :nick_contains,:size=>20 %></td>
            </tr>
            <tr>
              <th>用户组</th><td>
                <%= f.select :role_equals, {'不限制'=>'','普通会员'=>0,'机器人'=>1,'站点管理员'=>88} %>
              </td></tr>
            <tr>
              <th>用户经验值</th><td>
                <%= f.text_field :exp_greater_than,:size=>10 %> ~
                <%= f.text_field :exp_less_than,:size=>10 %>
              </td>
            </tr>
            <tr>
              <th>用户积分</th><td>
                <%= f.text_field :credit_greater_than,:size=>10 %> ~
                <%= f.text_field :credit_less_than,:size=>10 %>
              </td>
            </tr>
            <tr><th>空间创建时间</th><td colspan="3">
                <input type="text" name="dateline1" value="" size="10"> ~
                <input type="text" name="dateline2" value="" size="10"> (YYYY-MM-DD)
              </td>
            </tr>
            <tr><th>最后更新时间</th><td colspan="3">
                <input type="text" name="updatetime1" value="" size="10"> ~
                <input type="text" name="updatetime2" value="" size="10"> (YYYY-MM-DD)
              </td>
            </tr>
            <tr><th>结果排序</th>
              <td colspan="3">
                <select name="orderby">
                  <option value="id">默认排序</option>
                  <option value="created_at">建立时间</option>
                  <option value="last_request_at">访问时间</option>
                  <option value="viewnum">访问量</option>
                  <option value="exp">经验值</option>
                  <option value="credit">积分数</option>
                  <option value="followers">好友数</option>
                </select>
                <select name="ordersc">
                  <option value="desc" selected="">递减</option>
                  <option value="asc">递增</option>
                </select>
                <%= f.submit '搜索', :class=>'submit' %>
              </td>
            </tr>
          </tbody></table>
      </div>
    <% end %>



    <div class="bdrcontent">

      <form method="post" action="admincp.php?ac=space&amp;perpage=20&amp;page=1">
        <input type="hidden" name="formhash" value="e6c92636">
        <table cellspacing="2" cellpadding="2" class="listtable">
          <tbody><tr class="line">
              <th width="30">选择</th>
              <th width="55"></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th>操作</th>
            </tr>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <input type="checkbox" name="uids[]" value="1">
                </td>
                <td>
                  <a href="/u/<%= user[:_id] %>" target="_blank"></a>
                </td>
                <td>
                  <a href="/u/<%= user[:_id] %>" target="_blank"><%= user[:name] %></a>
                </td>
                <td>
                  <%= user[:email] %></td>
                <td class="gray">
                  <%= user[:exp] %> / <%= user[:credit] %></td>
                <td>
                  <%= user[:created_at] %><br>
                  <%= user[:last_request_at] %></td>
                <td><%= link_to '管理',edit_admin_user_path(user) %><br></td>
              </tr>
            <% end %>
          </tbody></table>
      </form></div>

    <div class="footactions">
      <input type="checkbox" id="chkall" name="chkall" onclick="checkAll(this.form, 'uids')">全选 &nbsp;&nbsp;
      <input type="radio" name="optype" value="1"> 通过实名
      <input type="radio" name="optype" value="2"> 取消实名
      <input type="radio" name="optype" value="3"> 清空实名

      <input type="radio" name="optype" value="4"> 发送邮件
      <input type="radio" name="optype" value="5"> 打招呼
      <input type="radio" name="optype" value="7"> 赠送道具
      <input type="radio" name="optype" value="6"> 清理CSS

      <input type="submit" name="listsubmit" value="提交" class="submit">
      
    </div>

  </div>
</div>

app/views/admin/users/new.html.erb
<div class="mainarea">
  <div class="maininner">
    <div class="tabs_header">
      <ul class="tabs">
        <li><a href="/admin/users"><span>管理用户</span></a></li>
		<li class="active"><a href="<%= new_admin_user_path %>"><span>新建用户</span></a></li>
      </ul>
    </div>
    <%= form_for @user, :url => admin_users_path do |f| %>
      <div class="bdrcontent">
        <table cellspacing="0" cellpadding="0" class="formtable">
          <tbody>
            <tr>
              <th style="width:12em;">昵称(以逗号分割)</th>
              <td><%= f.text_area :name, :class=>'t_input',:size=>'60x6' %></td>
            </tr>
          </tbody></table>
      </div>
      <div class="footactions">
        <%= f.hidden_field :role, :value => 1 %>
        <%= f.hidden_field :password, :value => 'o!h@i#m$y%r^o&b*o(t)' %>
        <%= f.hidden_field :password_confirmation, :value => 'o!h@i#m$y%r^o&b*o(t)' %>
        <%= f.submit '提交',:class=>'submit' %>
      </div>
    <% end %>
  </div>
</div>